### ISSUE TITLE
Is there a forum, or place to post questions about the book?

### ISSUE THREAD

**Issue by KansaiUser** [PacktPublishing/EngineeringMLOps#3]
I have purchased this book and I am currently reading it (chapter 4 ML Pipelines)
There is some procedure that I cannot follow since I don't understand it. 

Is there some place where I can ask for support?

Thanks

**Comment by rajat-packt** [comment]
Sorry that we could not provide the desired assistance this time :( 

At present we don't have any support forums dedicated for titles but if you'd like to, you can write to our customer support at customercare@packtpub.com and suggest that they create support forums or a platform, where people can seek help and discuss ideas for our published titles.

Alternatively, we can ask the author to provide assistance in the form of corrections if you come across any erratum in the book. Just create a new GitHub issue and describe the error/mistake in the book content, that you have encountered.
